alias tests_all='CLOUDLANGUAGETOOLS_CORE_TEST_UNRELIABLE=yes uv run pytest tests'
alias tests_fast='uv run pytest -n24 --dist=load tests'
alias tests_fast_audio='uv run pytest -n24 --dist=load tests/test_audio.py'
alias test_audio_mandarin_azure='uv run pytest tests/test_audio.py -k test_mandarin_azure'
alias package='./package.sh'
alias sync_languages_hypertts='scp cloudlanguagetools/languages.py anki:~/code/python/anki-hyper-tts/hypertts_addon/languages.py'
alias sync_voicelist_hypertts='uv run python utils/voice_list_hypertts.py && scp temp_data_files/hypertts_voicelist.py anki:~/code/python/anki-hyper-tts/hypertts_addon/services/voicelist.py'
alias tts_cli='uv run python utils/tts_cli.py'
alias tests_mock='CLOUDLANGUAGETOOLS_CORE_TEST_SERVICES=yes uv run pytest tests/test_mock_services.py'
