alias tests_all='CLOUDLANGUAGETOOLS_CORE_TEST_UNRELIABLE=yes pytest tests'
alias tests_fast='pytest -n24 --dist=load tests'
alias tests_fast_audio='pytest -n24 --dist=load tests/test_audio.py'
alias test_audio_mandarin_azure='pytest tests/test_audio.py -k test_mandarin_azure'
alias package='./package.sh'
alias sync_languages_hypertts='scp cloudlanguagetools/languages.py anki:~/code/python/anki-hyper-tts/hypertts_addon/languages.py'
alias sync_voicelist_hypertts='python utils/voice_list_hypertts.py && scp temp_data_files/hypertts_voicelist.py anki:~/code/python/anki-hyper-tts/hypertts_addon/services/voicelist.py'