import logging
import sys
import unittest

import getcheddar_utils

class TestGetCheddarUtils(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.utils = getcheddar_utils.GetCheddarUtils()

        logging.basicConfig(format='%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s', 
                            datefmt='%Y%m%d-%H:%M:%S',
                            stream=sys.stdout,
                            level=logging.DEBUG)

    def test_decode_webhook_new_subscription(self):
        data = {'activityActor': 'luc.wastiaux@xsmail.com',
        'activityDatetime': '2021-06-01T01:10:14+00:00',
        'activityType': 'newSubscription',
        'customer': {'campaignContent': '',
                    'campaignMedium': '',
                    'campaignName': '',
                    'campaignSource': '',
                    'campaignTerm': '',
                    'code': 'no1@spam.com',
                    'company': '',
                    'createdDatetime': '2021-06-01T01:10:13+00:00',
                    'email': 'languagetools+customer1@mailc.net',
                    'firstContactDatetime': '',
                    'firstName': 'Luc',
                    'gatewayToken': 'SIMULATED',
                    'id': '1e39d01a-c276-11eb-bed7-0eff6b8b8fd3',
                    'isTaxExempt': '0',
                    'key': 'd868455a94',
                    'lastName': 'Customer1',
                    'notes': '',
                    'referer': '',
                    'taxNumber': ''},
        'product': {'code': 'LANGUAGE_TOOLS',
                    'id': '53def3f0-bceb-11eb-bed7-0eff6b8b8fd3',
                    'name': 'Language Tools',
                    'subdomain': 'languagetools'},
        'subscription': {'cancelReason': '',
                        'cancelType': '',
                        'canceledDatetime': '',
                        'ccAddress': '',
                        'ccCity': '',
                        'ccCompany': '',
                        'ccCountry': 'US',
                        'ccEmail': '',
                        'ccExpirationDate': '2028-01-31',
                        'ccFirstName': 'Luc',
                        'ccLastFour': '0002',
                        'ccLastName': 'Customer1',
                        'ccState': '',
                        'ccType': 'amex',
                        'ccZip': '',
                        'createdDatetime': '2021-06-01T01:10:13+00:00',
                        'gatewayToken': 'SIMULATED',
                        'id': '1e3ee8e5-c276-11eb-bed7-0eff6b8b8fd3',
                        'invoice': {'billingDatetime': '2021-06-01T01:10:13+00:00',
                                    'charges': [{'code': 'SMALL_RECURRING',
                                                'createdDatetime': '2021-06-01T01:10:13+00:00',
                                                'description': '',
                                                'eachAmount': '5.0000',
                                                'id': '1e850a52-c276-11eb-bed7-0eff6b8b8fd3',
                                                'quantity': '1.0000',
                                                'type': 'recurring'}],
                                    'createdDatetime': '2021-06-01T01:10:13+00:00',
                                    'id': '1e8333d1-c276-11eb-bed7-0eff6b8b8fd3',
                                    'invoiceNumber': '2',
                                    'isInitial': 1,
                                    'items': [{'code': 'thousand_chars',
                                                'id': '382ca6fd-c274-11eb-bed7-0eff6b8b8fd3',
                                                'name': 'Thousand Chars',
                                                'quantity': 0}],
                                    'paidTransactionId': '1eae9c01-c276-11eb-bed7-0eff6b8b8fd3',
                                    'previousBillingDatetime': '',
                                    'taxRate': '',
                                    'transaction': {'amount': '5.00',
                                                    'gatewayToken': 'SIMULATED',
                                                    'id': '1eae9c01-c276-11eb-bed7-0eff6b8b8fd3',
                                                    'memo': '',
                                                    'parentId': '',
                                                    'paymentMethod': {'city': '',
                                                                        'company': '',
                                                                        'country': 'US',
                                                                        'createdDatetime': '2021-06-01T01:10:13+00:00',
                                                                        'creditCard': {'creditCardType': 'amex',
                                                                                    'firstSix': '370000',
                                                                                    'lastFour': '0002'},
                                                                        'email': '',
                                                                        'expirationDate': '2028-01-31',
                                                                        'firstName': 'Luc',
                                                                        'gatewayToken': 'SIMULATED',
                                                                        'gatewayTokenAux': '',
                                                                        'id': '11ebc276-1e3e-0e13-bed7-0eff6b8b8fd3',
                                                                        'lastName': 'Customer1',
                                                                        'method': 'cc',
                                                                        'postCode': '',
                                                                        'state': '',
                                                                        'street': '',
                                                                        'type': 'CreditCard'},
                                                    'response': 'approved',
                                                    'responseReason': 'SIMULATED '
                                                                        'approved '
                                                                        'payment',
                                                    'taxAmount': '',
                                                    'transactedDatetime': '2021-06-01T01:10:14+00:00'},
                                    'type': 'subscription'},
                        'method': 'cc',
                        'paymentMethod': {'city': '',
                                            'company': '',
                                            'country': 'US',
                                            'createdDatetime': '2021-06-01T01:10:13+00:00',
                                            'creditCard': {'creditCardType': 'amex',
                                                        'firstSix': '370000',
                                                        'lastFour': '0002'},
                                            'email': '',
                                            'expirationDate': '2028-01-31',
                                            'firstName': 'Luc',
                                            'gatewayToken': 'SIMULATED',
                                            'gatewayTokenAux': '',
                                            'id': '11ebc276-1e3e-0e13-bed7-0eff6b8b8fd3',
                                            'lastName': 'Customer1',
                                            'method': 'cc',
                                            'postCode': '',
                                            'state': '',
                                            'street': '',
                                            'type': 'CreditCard'},
                        'plan': {'billingFrequencyQuantity': '1',
                                'billingFrequencyUnit': 'months',
                                'code': 'SMALL',
                                'createdDatetime': '2021-06-01T00:57:28+00:00',
                                'description': '',
                                'id': '56561361-c274-11eb-bed7-0eff6b8b8fd3',
                                'isActive': '1',
                                'isFree': False,
                                'items': [{'code': 'thousand_chars',
                                            'id': '382ca6fd-c274-11eb-bed7-0eff6b8b8fd3',
                                            'isPeriodic': '1',
                                            'name': 'Thousand Chars',
                                            'overageAmount': '0.00',
                                            'quantityIncluded': 250}],
                                'name': 'Small',
                                'recurringChargeAmount': '5.00',
                                'recurringChargeCode': 'SMALL_RECURRING',
                                'setupChargeAmount': '0.00',
                                'setupChargeCode': 'SMALL_SETUP'}}}

        webhook_data = self.utils.decode_webhook(data)
        expected_data = {
            'type': 'newSubscription',
            'code': 'no1@spam.com',
            'email': 'languagetools+customer1@mailc.net',
            'thousand_char_quota': 250
        }
        self.assertEqual(webhook_data, expected_data)